# windowrule = suppressevent maximize, class:.* # You'll probably like this.

windowrule = stay_focused on, match:class Rofi

windowrule = float on, fullscreen on, match:class mpv

windowrule = float on, match:class org.telegram.desktop, match:title Media viewer
windowrule = fullscreen on, match:class org.telegram.desktop

layerrule = blur on, match:class waybar
