theme = "gruvbox-dark"
# diff_view = "side-by-side"   # or "unified"
diff_view = "unified"
ignore_whitespace = false
mouse = true
leader = ";"
comment_vim = true
review_watch_interval_ms = 1000
show_commits = false
show_file_list = false
